# Generated by Django 5.2.6 on 2026-02-22 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('price', models.IntegerField(verbose_name='Price')),
                ('image_url', models.CharField(max_length=254, verbose_name='Image URL')),
                ('description', models.CharField(max_length=254, verbose_name='Description')),
                ('cartegory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='menu.menucategory')),
            ],
        ),
    ]
