# Generated by Django 6.0.2 on 2026-02-18 06:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='menu',
            name='date_added',
            field=models.DateField(default=datetime.datetime(2026, 2, 18, 6, 36, 15, 948652, tzinfo=datetime.timezone.utc)),
        ),
    ]
