# Generated by Django 5.2.6 on 2026-02-22 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='cartegory',
            new_name='category',
        ),
    ]
